In [ ]:
   import numpy as np
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:

import numpy as np
a=np.array([[1,2],[3,8]])
print(a)
b=np.array([[2200],[10100]])
print(b)
np.linalg.solve(a,b)

[[1 2]
 [3 8]]
[[ 2200]
 [10100]]


array([[-1300.],
       [ 1750.]])

In [ ]:
pip install datetime

     |████████████████████████████████| 60 kB 2.9 MB/s 
     |████████████████████████████████| 251 kB 10.6 MB/s 


In [ ]:
pip install numpy
import datetime
a=[10,20,30]
b=[1,2,3]
#traditional python code
def dot_product(a,b):
  result=0
  for i, j in zip(a,b):
    result=result+i*j
  return result

before = datetime.now() 
for i in range(100000):
  dot_product(a,b)
after = datetime.now()
print('The time taken by traditional python:',after-before) 

#numpy library code
before=datetime.now()
for i in range(100000):
  np.dot(a,b)  #this is from numpy
after=datetime.now()

print('The time taken by numpy library:',after-before)

  

SyntaxError: ignored

In [ ]:
import numpy as np
l=[10,20,30]
print(type(l))
a=np.array(l)
print(type(a))
print(a)
print(a.ndim)
print(a.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[10 20 30]
1
int64


In [ ]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)
print(a.ndim)
print(a.size)
print(a.shape)
print(a.dtype)
a=np.array([10,20,10.5])
a=np.array([10,20,10.5],dtype=int)
a=np.array([10,20,10.5],dtype=str)

print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
2
9
(3, 3)
int64
['10' '20' '10.5']


In [ ]:
import  numpy as np
a=np.arange(11)
print(a)
b=np.linspace(0,1)
c=np.linspace(1,100,10,dtype=int)
print(c.ndim)
print(c)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]
1
[  1  12  23  34  45  56  67  78  89 100]
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [ ]:
import numpy as np
a=np.zeros(5)
print(a)
print(np.zeros((2,3,4),dtype=int))   # 3D array 
b=np.ones((10),dtype=int)
c=np.ones((5,2),dtype=int)
d=np.ones((2,3,4),dtype=int)
print(b)
print(c)
print(d)

[0. 0. 0. 0. 0.]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[1 1 1 1 1 1 1 1 1 1]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
import numpy as np
a=np.full(10,5)
print(a)
b=np.full((5,4),7)
print(b)
c=np.full((2,3,4),9)
print(c)

[5 5 5 5 5 5 5 5 5 5]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [ ]:
import numpy as np
print(np.eye(5,dtype=int))
print(np.eye(5,k=2,dtype=int))
print(np.identity((3),dtype=int))
 

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
import numpy

print(np.random.randint(10,20))
print(np.random.randint(1,9,size=10))
print(np.random.randint(100,size=(3,5)))
print(np.random.randint(100,size=(2,3,4)))



12
[2 6 1 3 3 2 3 3 8 5]
[[40 91 27  4 87]
 [66 18 10 13 54]
 [23 44 99 44 52]]
[[[45  2 81 30]
  [58 66 36 64]
  [89 53 72 67]]

 [[90 12 18 17]
  [88 65 14 70]
  [34 63 62 58]]]


In [ ]:
import numpy as np  
print(np.random.randn())
print(np.random.randn(5))
print(np.random.randn(3,2))
print(np.random.normal(10,4,size=10))

-0.9709688073229483
[ 0.15598637 -0.25796982 -0.28167733 -0.57810791  0.57625327]
[[-1.37496803  0.46946752]
 [ 0.3914898  -0.07796564]
 [-0.24362508  0.28323019]]
[ 1.4315532  11.15234308  7.1707236  10.58191587  7.12797688  9.70899591
 16.04575817  8.25542152  6.79936067 13.33469441]
[0 1 2 3 4 5 6 7 8]
[2 5 8 7 0 3 6 4 1]
[2 6 1 0 7 4 5 3 8]


In [ ]:
import numpy as np
a=np.arange(9)
print(a)
np.random.shuffle(a)
print(a)
np.random.shuffle(a)
print(a)
a=np.random.randint(1,101,size=(6,5))
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8]
[5 2 3 8 1 0 7 4 6]
[3 6 2 1 7 5 0 4 8]
[[82 88 91 83  3]
 [30 78 93  7 87]
 [14 88 58 90  3]
 [55 12 33  4 45]
 [67 98 56  9 47]
 [13  7  6 33 19]]
[[14 88 58 90  3]
 [67 98 56  9 47]
 [13  7  6 33 19]
 [82 88 91 83  3]
 [30 78 93  7 87]
 [55 12 33  4 45]]


In [ ]:
import numpy as np
a=np.arange(48).reshape(4,3,4)
print(a)
np.random.shuffle(a)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
[[[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(5,)
5
int64
8


In [ ]:
import numpy as np
a=np.array([[10,20,30],[40,50,60]])
print(a)
print(a[0][2])
print(a[1][1])
print(a[-1][-2])
b=np.random.randint(1,20,size=(2,3,4))
print(b)

In [ ]:
import numpy as np
a=np.array([[10,20],[30,40],[50,60]]) 
print(a[0:1,:])
print(a[::2,:])
print(a[:2,1:2])
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(b)
print(b[:2,:])
print(b[:,:2])
print(b[:,::2])
print(b[::3,::3])

 

[[10 20]]
[[10 20]
 [50 60]]
[[20]
 [40]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[ 1  4]
 [13 16]]


In [ ]:
#Session 10
import numpy as np
l=[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]
a=np.array(l)
print(a)
print(a[:2,:,:1])
print(a[:,:1,:])
print(a[:,::2,:])
print(a[:,:2,1:3])
print(a[:,::2,::3])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [17]
  [21]]]
[[[ 1  2  3  4]]

 [[13 14 15 16]]]
[[[ 1  2  3  4]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [21 22 23 24]]]
[[[ 2  3]
  [ 6  7]]

 [[14 15]
  [18 19]]]
[[[ 1  4]
  [ 9 12]]

 [[13 16]
  [21 24]]]


In [ ]:
import numpy as np
a=np.arange(10,101,10)
print(a)
indices=np.array([2,4,5,8])
print(a[indices])
#OR
l=[2,4,5,8]
print(a[l])
print(a[[0,4,6,9]])
print('-----------------2D indexing--------------------------------')
l=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16 ]]
a=np.array(l)
print(a)
print()
print(a[[0,1,2,3],[0,1,2,3]])
print(a[[0,1,2,3],[1,3,0,2]])
print(a[[0,1,2,3,3,3,3],[0,0,0,0,1,2,3]])
print(a[[0,1,2],[0]])
print(a[[0],[0,1,2]])
print('-'*50)
print('###### 3D indexing')
l=[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16 ],[17,18,19,20],[21,22,23,24]]]
a=np.array(l)
print(a)
print(a[[0,1],[1,1],[2,1]])


[ 10  20  30  40  50  60  70  80  90 100]
[30 50 60 90]
[30 50 60 90]
[ 10  50  70 100]
-----------------2D indexing--------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[ 1  6 11 16]
[ 2  8  9 15]
[ 1  5  9 13 14 15 16]
[1 5 9]
[1 2 3]
--------------------------------------------------
###### 3D indexing
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[ 7 18]


In [ ]:
#Session - 10
import numpy as np
a=np.array([10,20,30,40])
print(a>25)
b_a=a>25
print(a[b_a])
print(a[a>25])

print('#'*50)
a=np.array([10,-5,20,40,-3,-3,75])
print(a[a<0])   #To find all negative no.
print(a[a>0])   #To find all positive no.
print(a[a%2==0])    #To find even no.
print(a[a%2!=0])    #To find odd no.
print(a[a%5==0])   #To get no. divisible by 5 

print('#'*50)
a=np.arange(1,26).reshape(5,5)
print(a)
print(a[a%2==0])     #To get even no.  
print(a[a%10==0])



[False False  True  True]
[30 40]
[30 40]
##################################################
[-5 -3 -3]
[10 20 40 75]
[10 20 40]
[-5 -3 -3 75]
[10 -5 20 40 75]
##################################################
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 2  4  6  8 10 12 14 16 18 20 22 24]
[10 20]


In [ ]:
import numpy as np
a=np.arange(10,100,10)
print(a)
for i in a:
  print(i)

print('#'*50)
  
print(a)
for x in a:
  for y in x:
    print(y)

print('#'*50)
a=np.arange(10,81,10).reshape(2,2,2)
print(a)
for x in a:
  for y in x:
    for z in y:
      print(z)

[10 20 30 40 50 60 70 80 90]
10
20
30
40
50
60
70
80
90
##################################################
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
10
20
30
40
50
60
70
80
90
100
##################################################
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
10
20
30
40
50
60
70
80


In [ ]:
import numpy as np
a=np.arange(10,100,10)
for x in np.nditer(a):
  print(x)

print('#'*50)
a=np.arange(10,101,10).reshape(2,5)     # 2D 
for x in np.nditer(a):
  print(x)
print('#'*50)
a=np.arange(10,81,10).reshape(2,2,2)     # 3D array
for x in np.nditer(a):
  print(x)

print('#'*50)
#Iterate element of sliced array
import numpy as np
a=np.arange(10,91,10).reshape(3,3)
print(a)
for x in np.nditer(a[:,:2]):
  print(x)
print()
print('#'*50)
#TO get required datatype
a=np.arange(10,91,10).reshape(3,3)
print(a)
for x in np.nditer(a,flags=['buffered'],op_dtypes=['float']):
    print(x)





10
20
30
40
50
60
70
80
90
##################################################
10
20
30
40
50
60
70
80
90
100
##################################################
10
20
30
40
50
60
70
80
##################################################
[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
20
40
50
70
80

##################################################
[[10 20 30]
 [40 50 60]
 [70 80 90]]
10.0
20.0
30.0
40.0
50.0
60.0
70.0
80.0
90.0


In [ ]:
#Session- 12  
#Iterate elements by using ndenumerate function
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
for pos,element in np.ndenumerate(a):
  print(f'{element} element present at index: {pos}')

print('#'*50)
a=np.arange(10,91,10).reshape(3,3)
for pos,element in np.ndenumerate(a):
  print(f'{element} element present at index: {pos}')

#Arithmetic OPerator
print('#'*50)
a=np.array([10,20,30,40,50,60])       # 1D array
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a//2)
print(a**2)

#For 2D array
print('#'*50)
a=np.arange(10,61,10).reshape(2,3)
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a//2)
print(a**2)
print(a/0)

#Array with array
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(b/a)
print(b**a)



10 element present at index: (0,)
20 element present at index: (1,)
30 element present at index: (2,)
40 element present at index: (3,)
50 element present at index: (4,)
60 element present at index: (5,)
70 element present at index: (6,)
80 element present at index: (7,)
##################################################
10 element present at index: (0, 0)
20 element present at index: (0, 1)
30 element present at index: (0, 2)
40 element present at index: (1, 0)
50 element present at index: (1, 1)
60 element present at index: (1, 2)
70 element present at index: (2, 0)
80 element present at index: (2, 1)
90 element present at index: (2, 2)
##################################################
[12 22 32 42 52 62]
[ 8 18 28 38 48 58]
[ 20  40  60  80 100 120]
[ 5. 10. 15. 20. 25. 30.]
[ 5 10 15 20 25 30]
[ 100  400  900 1600 2500 3600]
##################################################
[[10 20 30]
 [40 50 60]]
[[12 22 32]
 [42 52 62]]
[[ 8 18 28]
 [38 48 58]]
[[ 20  40  60]
 [ 80 100 120]]
[

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: RuntimeWarning: divide by zero encountered in true_divide


In [ ]:
import numpy as np
a=np.arange(6)
print(a/0)


[nan inf inf inf inf inf]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
#Session - 12
#Broadcasting
import numpy as np
a=np.array([[10,20],[30,40],[50,60]])
b=np.array([10,20])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

print('#'*50)
import numpy as np
a=np.array([[10],[20],[30]])
b=np.array([10,20,30])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[20 40]
 [40 60]
 [60 80]]
[[ 0  0]
 [20 20]
 [40 40]]
[[ 100  400]
 [ 300  800]
 [ 500 1200]]
[[1. 1.]
 [3. 2.]
 [5. 3.]]
##################################################
[[20 30 40]
 [30 40 50]
 [40 50 60]]
[[  0 -10 -20]
 [ 10   0 -10]
 [ 20  10   0]]
[[100 200 300]
 [200 400 600]
 [300 600 900]]
[[1.         0.5        0.33333333]
 [2.         1.         0.66666667]
 [3.         1.5        1.        ]]


In [ ]:
 #Session - 14
 import numpy as np
 a=np.arange(10)
 a[0]=77
 print(a)
 b=a.reshape(2,5)
 print(b)
 a=np.arange(24)
 print(a)
 print(a.reshape(2,4,3))
 print(a.reshape(6,-1))
#print(a.reshape(-1,-1))     #It will show error
#print(a.reshape(5,-1))      #It will also show error

print('#'*50)
a=np.arange(1,6)
print(a)
b=np.resize(a,(4,3))
print(b)
a=np.arange(1,6)
print(a.resize(5,3))


 


[77  1  2  3  4  5  6  7  8  9]
[[77  1  2  3  4]
 [ 5  6  7  8  9]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
##################################################
[1 2 3 4 5]
[[1 2 3]
 [4 5 1]
 [2 3 4]
 [5 1 2]]
None


In [ ]:
#Session 15
#flatten() function :
import numpy as np
a=np.arange(8).reshape(2,4)
print(a)
b=a.flatten()
print(b)
a[0][0]=777
print(a)
print(b)

print()
a=np.arange(12).reshape(4,3)
print(a)
print(a.flatten())
print()
a=np.arange(24).reshape(2,3,4)
a[0][0][0]=999
print(a)
print(a.ravel())

print()
a=np.arange(1,5).reshape(2,2)
print(a)
b=np.transpose(a)
a[0,0]=555
print(a)
print(b)

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]
[[777   1   2   3]
 [  4   5   6   7]]
[0 1 2 3 4 5 6 7]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[[999   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]
[999   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]

[[1 2]
 [3 4]]
[[555   2]
 [  3   4]]
[[555   3]
 [  2   4]]


In [ ]:
#Session - 16
import numpy as np
a=np.arange(1,25).reshape(2,3,4)
print(a) 
print(np.transpose(a))
b=np.transpose(a,axes=(1,0,2))
print(b.shape)
print(b)
b=np.transpose(a,(2,0,1))
print(b.shape)
print(b)

b=a.T
print(b)

print('#'*50)
a=np.arange(24).reshape(2,3,4)
print(a)
b=np.swapaxes(a,0,2)
print(b.shape)
print(b)
b=np.swapaxes(a,1,2)
print(b.shape)
 

  




[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
(3, 2, 4)
[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]
(4, 2, 3)
[[[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]

 [[ 4  8 12]
  [16 20 24]]]
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
##################################################
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(4, 3, 2)
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(2, 4, 3)


In [ ]:
#Session - 17
import numpy as np
a=np.arange(4)
b=np.arange(5)
c=np.arange(3)
print(np.concatenate((a,b)))
print(np.concatenate((a,b,c)))

print()
a=np.arange(4)
b=np.arange(5)     
c=np.arange(3)
d=np.empty(12,dtype=int)
np.concatenate((a,b,c),out=d)
print(d)
#print(np.concatenate((a,b),dtype=float))
print()
a=np.arange(10,61,10).reshape(3,2)
b=np.arange(70,101,10).reshape(2,2)
print(a)
print(b)
print(np.concatenate((a,b)))
print(np.concatenate((a,b),axis=None))

print('#'*30)
a=np.arange(6).reshape(3,2)
b=np.arange(9).reshape(3,3)
print(np.concatenate((a,b),axis=1))

print('-'*50)
print('##CONCATENATION OF 3D ARRAY##')
a=np.arange(8).reshape(2,2,2)
b=np.arange(8).reshape(2,2,2)
print(a)
print(np.concatenate((a,b)))
print()
print(np.concatenate((a,b),axis=1))
print()
print(np.concatenate((a,b),axis=2))
print()
print()
a=np.arange(12).reshape(2,3,2)
b=np.arange(18).reshape(2,3,3)
print(a)
print(b)
print(np.concatenate((a,b),axis=2))   #Concatenation along axis 0 and 1 is not possible

print('-'*50)
print('## STACK() FUNCTION ##')
a=np.array([10,20,30])
b=np.array([40,50,60])
print(np.stack((a,b)))
print()
print(np.stack((a,b),axis=1))
    









[0 1 2 3 0 1 2 3 4]
[0 1 2 3 0 1 2 3 4 0 1 2]

[0 1 2 3 0 1 2 3 4 0 1 2]

[[10 20]
 [30 40]
 [50 60]]
[[ 70  80]
 [ 90 100]]
[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]
[ 10  20  30  40  50  60  70  80  90 100]
##############################
[[0 1 0 1 2]
 [2 3 3 4 5]
 [4 5 6 7 8]]
--------------------------------------------------
##CONCATENATION OF 3D ARRAY##
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]

 [[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[0 1]
  [2 3]
  [0 1]
  [2 3]]

 [[4 5]
  [6 7]
  [4 5]
  [6 7]]]

[[[0 1 0 1]
  [2 3 2 3]]

 [[4 5 4 5]
  [6 7 6 7]]]


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 0  1  0  1  2]
  [ 2  3  3  4  5]
  [ 4  5  6  7  8]]

 [[ 6  7  9 10 11]
  [ 8  9 12 13 14]
  [10 11 15 16 17]]]
--------------------------------------------------
## STACK() FUNCTION ##
[[10 20 30]
 [40 50 60]]

[[10 40]
 [20 50]
 [30 60]]


In [ ]:
#Session - 18
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]]) 
print(np.stack((a,b)))
print(np.stack((a,b),axis=1))
print(np.stack((a,b),axis=2))

print('-'*40)
a=np.arange(1,7).reshape(3,2)
b=np.arange(7,13  ).reshape(3,2)
c=np.arange(13,19).reshape(3,2)
print(a)
print(b)
print(c)
print()
print(np.stack((a,b,c)))
print()
print(np.stack((a,b,c),axis=1))
print()
print(np.stack((a,b,c),axis=2))

print()
print('-----------Stacking of three 1 D array----------')
a=np.arange(4)
b=np.arange(4,8)
c=np.arange(8,12)
print(a)
print(b)
print(c)
print(np.stack((a,b,c)))
print(np.stack((a,b,c),axis=1))

print()
print('-----------V STACK FUNCTION-----------')
a=np.array([10,20,30,40])
b=np.array([50,60,70,80])
print(np.vstack((a,b)))

print()
a=np.arange(1,25).reshape(2,3,4)
b=np.arange(25,49).reshape(2,3,4)
print(a)
print(b)
print(np.vstack((a,b)))

print()
print('-------------H stack function------------')
a=np.array([10,20,30,40])
b=np.array([50,60,70,80,90,100])
print(np.hstack((a,b)))
print()
#For 2 D
a=np.arange(1,7).reshape(3,2)
b=np.arange(7,16).reshape(3,3)
print(np.hstack((a,b)))

print()
a=np.array([[1],[2],[3]])
b=np.array([[2],[3],[4]])
print(np.dstack((a,b)))
  






 





[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
----------------------------------------
[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[13 14]
 [15 16]
 [17 18]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]

[[[ 1  2]
  [ 7  8]
  [13 14]]

 [[ 3  4]
  [ 9 10]
  [15 16]]

 [[ 5  6]
  [11 12]
  [17 18]]]

[[[ 1  7 13]
  [ 2  8 14]]

 [[ 3  9 15]
  [ 4 10 16]]

 [[ 5 11 17]
  [ 6 12 18]]]

-----------Stacking of three 1 D array----------
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

-----------V STACK FUNCTION-----------
[[10 20 30 40]
 [50 60 70 80]]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]

 [[37 38 39 40]
  [41 42 

In [ ]:
#Session - 19
#Splitting of arrays....
import numpy as np
a=np.arange(1,10)
print(np.split(a,3))     

print('------SPLITING BASED ON AXIS- 1 --------')
a=np.arange(1,25).reshape(6,4)
print(a)
print(np.split(a,2))
print()
print(np.split(a,4,axis=1))

print()
a=np.arange(10,101,10)
print(np.split(a,[3,7]))
print(np.split(a,[2,5,7]))
print()
a=np.arange(1,19).reshape(3,6)
print(np.split(a,[1,3,5],axis=1))
print()
print(np.split(a,[2,4,4],axis=1))

print('---------V SPLIT () FUNCtion-----')
a=np.arange(1,13).reshape(6,2)
print(a)
print(np.split(a,2))
print(np.split(a,6))

print('---------H SPLIT () FUNCtion-----')
a=np.arange(10)
print(np.split(a,2))
print(np.split(a,5))
print('--------- 2d   HSPLIT() --------')
a=np.arange(1,13).reshape(2,6)
print(np.hsplit(a,2))
print()
a=np.arange(24).reshape(4,6)
print(np.hsplit(a,[2,4]))
print(np.hsplit(a,[1,3,5]))


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
------SPLITING BASED ON AXIS- 1 --------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]

[array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]]), array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24]])]

[array([10, 20, 30]), array([40, 50, 60, 70]), array([ 80,  90, 100])]
[array([10, 20]), array([30, 40, 50]), array([60, 70]), array([ 80,  90, 100])]

[array([[ 1],
       [ 7],
       [13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]]), array([[ 6],
       [12],
       [1

In [ ]:
#Session - 20
#array_split() Function
import numpy as np
a=np.arange(24).reshape(2,3,4)
print(np.dsplit(a,2))
print()
#array_split() Function
a=np.arange(10,101,10)
print(np.array_split(a,3))
print()
a=np.arange(11)
print(np.array_split(a,3))
print()
#For 2D 
a=np.arange(24).reshape(6,4)
print(np.array_split(a,4))
print('-----------------SORTING OF ARRAYS-----------')
a=np.array([70,20,40,50,10,30,60,90,80])
print(np.sort(a))
print(np.sort(a)[::-1])    #FOR  reverse order
print(-np.sort(-a))       #FOR  reverse order
a=np.array(['cat','rat','dog','bat','vat'])
print(np.sort(a))
print(np.sort(a)[::-1])    #Reverse order
#print(-np.sort(-a))    #error
print()
#For 2D array
a=np.array([[40,20,70],[30,20,60],[70,90,80]])
print(np.sort(a))
print(np.sort((a),axis=0))
 


[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]

[array([10, 20, 30, 40]), array([50, 60, 70]), array([ 80,  90, 100])]

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
-----------------SORTING OF ARRAYS-----------
[10 20 30 40 50 60 70 80 90]
[90 80 70 60 50 40 30 20 10]
[90 80 70 60 50 40 30 20 10]
['bat' 'cat' 'dog' 'rat' 'vat']
['vat' 'rat' 'dog' 'cat' 'bat']

[[20 40 70]
 [20 30 60]
 [70 80 90]]
[[30 20 60]
 [40 20 70]
 [70 90 80]]


In [ ]:
#Session - 21
#Searching elements of nd array
import numpy as np 
a=np.array([3,4,5,3,2,5.8,7,2,9])
print(a)
print(np.where(a==5))
print(np.where(a%2 !=0))   #Elements divisible by 3
print(np.where(a%3 ==0))
print()
#replace odd no. with 9999 and even no. with 8888
b=np.where(a%2==0,8888,9999)
print(b)
#Replace odd no. with 999
b=np.where(a%2 != 0,999,a)
print(b)  
print()
#For 2D array
a=np.arange(12).reshape(4,3)
print(a)
b=np.where(a%5==0)
print(b)
print(a[b])
b=np.where(a%5==0,999,a)    #replacement of multiple of 5 with 999
print(b)

print()
print('----------SEARCHSORTED FUNCTION------------')
a=np.arange(0,31,5)
print(a)
print(np.searchsorted(a,5))
print(np.searchsorted(a,13))
print()
a=np.array([3,5,7,6,7,9,4,10,15,6])
a=np.sort(a)
print(np.searchsorted(a,6))
print(np.searchsorted(a,6,side='right'))


  
  



[3.  4.  5.  3.  2.  5.8 7.  2.  9. ]
(array([2]),)
(array([0, 2, 3, 5, 6, 8]),)
(array([0, 3, 8]),)

[9999 8888 9999 9999 8888 9999 9999 8888 9999]
[999.   4. 999. 999.   2. 999. 999.   2. 999.]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(array([0, 1, 3]), array([0, 2, 1]))
[ 0  5 10]
[[999   1   2]
 [  3   4 999]
 [  6   7   8]
 [  9 999  11]]

----------SEARCHSORTED FUNCTION------------
[ 0  5 10 15 20 25 30]
1
3

3
5


In [ ]:
#Session - 22
#insert()
import numpy as np
a=np.arange(10)
print(a)
b=np.insert(a,2,777)
print(b)
b=np.insert(a,[2,5],999)
print(b)
print()
b=np.insert(a,[2,5],[777,999])
print(b)
print()
print(np.insert(a,2,123.4332))
print(np.insert(a,5,True))

print()
print('----------Insertinng into 2D array----------')
a=np.arange(10,41,10).reshape(2,2)
print(np.insert(a,1,100))   #Here axis is None
print()
#To insert new row
print(np.insert(a,1,100,axis=0)) 
print()
print(np.insert(a,1,[100,200],axis=0))
print()
#To insert new column
print(np.insert(a,1,100,axis=1))
print()
print(np.insert(a,1,[100,200],axis=1))
print()

print(np.insert(a,0,[100,200],axis=-1))

print()
print('----------Append()Function-----------')
# 1D array
a=np.arange(10)
print(np.append(a,99))
print(np.append(a,[10,20,30]))
print(np.append(a,10.5))
print(np.append(a,'durga'))
print(np.append(a,True))
print(np.append(a,10+20j))

print()
print('-----Append function for 2D array------')
a=np.arange(10,41,10).reshape(2,2)
print(a)
print(np.append(a,70))
print()
#Append row
print(np.append(a,[[70,80]],axis=0))
print()
#print(np.append(a,[70,80],axis=0))    #Error
print(np.append(a,[[70,80],[90,100]],axis=0))
print()
#Append  column
print(np.append(a,[[70],[80]],axis=1))
print(np.append(a,[[70,80],[90,100]],axis=1))
 

[0 1 2 3 4 5 6 7 8 9]
[  0   1 777   2   3   4   5   6   7   8   9]
[  0   1 999   2   3   4 999   5   6   7   8   9]

[  0   1 777   2   3   4 999   5   6   7   8   9]

[  0   1 123   2   3   4   5   6   7   8   9]
[0 1 2 3 4 1 5 6 7 8 9]

----------Insertinng into 2D array----------
[ 10 100  20  30  40]

[[ 10  20]
 [100 100]
 [ 30  40]]

[[ 10  20]
 [100 200]
 [ 30  40]]

[[ 10 100  20]
 [ 30 100  40]]

[[ 10 100  20]
 [ 30 200  40]]

[[100  10  20]
 [200  30  40]]

----------Append()Function-----------
[ 0  1  2  3  4  5  6  7  8  9 99]
[ 0  1  2  3  4  5  6  7  8  9 10 20 30]
[ 0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.5]
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' 'durga']
[0 1 2 3 4 5 6 7 8 9 1]
[ 0. +0.j  1. +0.j  2. +0.j  3. +0.j  4. +0.j  5. +0.j  6. +0.j  7. +0.j
  8. +0.j  9. +0.j 10.+20.j]

-----Append function for 2D array------
[[10 20]
 [30 40]]
[10 20 30 40 70]

[[10 20]
 [30 40]
 [70 80]]

[[ 10  20]
 [ 30  40]
 [ 70  80]
 [ 90 100]]

[[10 20 70]
 [30 40 80]]


In [ ]:
#Session-23
#Deletion of elements
import numpy as np
a=np.arange(10,101,10)
print(a)
print(np.delete(a,3))
print(np.delete(a,[0,4,6]))    #To delete elements present at index 0 ,4,6
print(np.delete(a,np.s_[2:6]))    #To delete elements from 2nd index to 5th index
print()
print(np.delete(a,np.s_[:]))     #To delete whole array
print(np.delete(a,range(2,6)))   #Acceptable but not recommended to use range

print()
print('-----------2D array--------')
a=np.arange(1,13).reshape(3,4)
print(a)
print(np.delete(a,1))
print(np.delete(a,0,axis=0))   #To delete first row
print()
print(np.delete(a,[0,2],axis=0))
print()
print(np.delete(a,np.s_[:2],axis=0))

print()
print('-----Coloumn wise deletion')
print(np.delete(a,0,axis=1))
print(np.delete(a,[0,2],axis=1))
print(np.delete(a,np.s_[::3],axis=1))
print(np.delete(a,np.s_[1:],axis=1))

print()
print('---------Deletion for 3D array--------')
a=np.arange(24).reshape(2,3,4)
print(a)
print()
print(np.delete(a,0,axis=0))  #To delete first 2D array
print()
print(np.delete(a,1,axis=0))     #To delete second 2D array
print()
print(np.delete(a,0,axis=1))
print()
print(np.delete(a,1,axis=1))
print()
print(np.delete(a,[0,2],axis=1))
print()
print(np.delete(a,2,axis=1))
print()
print(np.delete(a,0,axis=2))
print()
print(np.delete(a,np.s_[1:],axis=2))


print()
print()
print()
a=np.arange(12).reshape(4,3)
b=np.delete(a,3,axis=0)
print(np.append(b,[[70,80,90]],axis=0))










[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  50  60  70  80  90 100]
[ 20  30  40  60  80  90 100]
[ 10  20  70  80  90 100]

[]
[ 10  20  70  80  90 100]

-----------2D array--------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  3  4  5  6  7  8  9 10 11 12]
[[ 5  6  7  8]
 [ 9 10 11 12]]

[[5 6 7 8]]

[[ 9 10 11 12]]

-----Coloumn wise deletion
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
[[ 2  4]
 [ 6  8]
 [10 12]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[1]
 [5]
 [9]]

---------Deletion for 3D array--------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]

[[[ 4  5  6  7]
  [ 8  9 10 11]]

 [[16 17 18 19]
  [20 21 22 23]]]

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [20 21 22 23]]]

[[[ 4  5  6  7]]

 [[16 17 18 19]]]

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[12 13 14 15]
  [16 17 18 19]]]

[[[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]]

In [ ]:
#Session - 24
import numpy as np
a=np.array([[1,2],[3,4]])
m=np.matrix([[1,2],[3,4]])
print(a)
print(m)
print()
print(a+a)
print(m+m)
print()
print(a*a)       #Element level multiplication will be happen
print(m*m)       #Matrix multiplication will be happen
print()
# ** (power operator)
print(a**2)
print(m**2)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]]

[[2 4]
 [6 8]]
[[2 4]
 [6 8]]

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [ ]:
#Session - 25
#LINEAR ALGEBRA FUNCTION FROM LINALG() MODULE  
#inv() function
import numpy as np
a=np.arange(8).reshape(2,2,2)
print(np.linalg.inv(a))

print()
#matrix_power()
a=np.array([[1,2],[3,4]])
print(np.linalg.matrix_power(a,0))
print(np.linalg.matrix_power(a,2))
print(np.linalg.matrix_power(a,-2))
print()

#det() function (determinant function)
print(np.linalg.det(a))
a=np.arange(8).reshape(2,2,2)
print(np.linalg.det(a))
print()

#solve() function
a=[[1,1],[3,8]]
b=np.array([2200,10100])
print(np.linalg.solve(a,b))

print()
a=np.array([[-4,7,-2],[1,-2,1],[2,-3,1]])
b=np.array([2,3,-4])
print(np.linalg.solve(a,b))




[[[-1.5  0.5]
  [ 1.   0. ]]

 [[-3.5  2.5]
  [ 3.  -2. ]]]

[[1 0]
 [0 1]]
[[ 7 10]
 [15 22]]
[[ 5.5  -2.5 ]
 [-3.75  1.75]]

-2.0000000000000004
[-2. -2.]

[1500.  700.]

[-13.  -6.   4.]


In [ ]:
#Session - 26
import numpy as np
a=np.array([[10,20,30],[40,50,60]])     #2D arraay
#save/serialize ndarray object to a file
np.save('out.npy',a)

#load/deserialized ndarray object from a file
out_array=np.load('out.npy')
print(out_array)

b=np.array([[70,80],[90,100]])

np.savez('out.npz',a,b)   #save
npzfileobj=np.load('out.npz')
print()
print(npzfileobj.files)
print()
print(npzfileobj['arr_0'])
print(npzfileobj['arr_1'])



[[10 20 30]
 [40 50 60]]
['arr_0', 'arr_1']
[[10 20 30]
 [40 50 60]]
[[ 70  80]
 [ 90 100]]


In [ ]:
#Session - 27
import numpy as np
a1=np.array([['Sunny',1000],['Bunny',2000],['Munni',3000],['chinny',4000]])

#save this ndarray to a text file
np.savetxt('out.txt',a1,fmt='%s %s')

#reading ndarray from the text file
a2=np.loadtxt('out.txt',dtype='str')
print(a2)

print()
print()
#BAsic statistic with numpy
a=np.array([10,17,9,4,45,221])
print(np.min(a))
print(np.amin(a))
print(a.min())
a=np.array([[100,20,30],[10,20,34],[45,15,18],[56,98,4],[2,46,32]])
print(a)
print(np.min(a))
print(np.min(a,axis=0))  #returns a minimum row and that row contain 3 element
print(np.min(a,axis=1))  #returns a minimum column that contain 5 elements
print()
a=np.arange(24).reshape(6,4)
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))
print()
a=np.arange(24).reshape(6,4)
np.random.shuffle(a)
print(a)
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

print()
#Finding Max
a=np.array([10,17,9,4,45,221])
print(np.max(a))
print(np.amax(a))
print(a.max())
a=np.array([[100,20,30],[10,20,34],[45,15,18],[56,98,4],[2,46,32]])
print(a)
print(np.max(a))
print(np.max(a,axis=0))  #returns a minimum row and that row contain 3 element
print(np.max(a,axis=1))  #returns a minimum column that contain 5 elements
print()

#Finding Sum
a=np.arange(6)
print(a)
print(np.sum(a))
a=np.arange(9).reshape(3,3)
print(a)
print(a.sum)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))



[['Sunny' '1000']
 ['Bunny' '2000']
 ['Munni' '3000']
 ['chinny' '4000']]


4
4
4
[[100  20  30]
 [ 10  20  34]
 [ 45  15  18]
 [ 56  98   4]
 [  2  46  32]]
2
[ 2 15  4]
[20 10 15  4  2]

0
[0 1 2 3]
[ 0  4  8 12 16 20]

[[ 4  5  6  7]
 [ 0  1  2  3]
 [20 21 22 23]
 [ 8  9 10 11]
 [16 17 18 19]
 [12 13 14 15]]
0
[0 1 2 3]
[ 4  0 20  8 16 12]

221
221
221
[[100  20  30]
 [ 10  20  34]
 [ 45  15  18]
 [ 56  98   4]
 [  2  46  32]]
100
[100  98  34]
[100  34  45  98  46]

[0 1 2 3 4 5]
15
[[0 1 2]
 [3 4 5]
 [6 7 8]]
<built-in method sum of numpy.ndarray object at 0x7eff5d72cbd0>
36
[ 9 12 15]
[ 3 12 21]


In [ ]:
#Session - 28
# To find Mean
print('--------MEan-------')
import numpy as np
a=np.arange(5)
print(np.mean(a))
print(a.mean())
a=np.arange(9).reshape(3,3)
print(a)
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1,dtype=int))  

print()
print()
#To find Median
print('-------------MEDIAN---------------')
a=np.array([10,20,30])
print(np.median(a))
a=np.array([10,20,30,40])
print(np.median(a))
print()
#For 2D
a=np.arange(9).reshape(3,3)
print(a)
print(np.median(a))
print(np.median(a,axis=0))
print(np.median(a,axis=1))
print()
a=np.arange(16).reshape(4,4)
print(a)
print(np.median(a))
print(np.median(a,axis=0))
print(np.median(a,axis=1))
print()

print('----------VARIANCE------------')
a=np.array([1,2,3,4,5])
print(np.var(a))
print()
a=np.arange(6).reshape(2,3)
print(a)
print(np.var(a))  
print(np.var(a,axis=0))
print(np.var(a,axis=1))

print()
print('----------STep deviation---------')
a=np.array([1,2,3,4,5])
print(np.std(a))
print()
a=np.arange(9).reshape(3,3)
print(a)
print(np.std(a))  
print(np.std(a,axis=0))
print(np.std(a,axis=1))

print()
print('---------Numpy mathematical functions------')
a=np.arange(5)
print(np.exp(a))
print(np.sqrt(a))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

print()
print('------------Find Unique elements---------')
a=np.array([1,1,1,2,3,4,3,2,4,5,4,5,1,6,4,3,2,3,2,5])
print(np.unique(a))
#To get unique elements along with indices
print(np.unique(a,return_index=True))
items,indices=np.unique(a,return_index=True)
print('items:',items)
print('items:',indices)
print()
items,counts=np.unique(a,return_counts=True)
print('items :',items)
print('Counts:',counts)
print()
items,indices,counts=np.unique(a,return_index=True,return_counts=True)
print('items :',items)
print('indices:',indices)
print('Counts:',counts)
for item,index,count in zip(np.nditer(items),np.nditer(indices),np.nditer(counts)):
  print(f'Element {item} occurred {count} times and its first occurrence index:{index}')

print()
a=np.array(['a','a','b','c','c','a','d','d','c','b','e','a','e','c'])
items,indices,counts=np.unique(a,return_index=True,return_counts=True)
for item,index,count in zip(np.nditer(items),np.nditer(indices),np.nditer(counts)):
  print(f'Element {item} occurred {count} times and its first occurrence index:{index}')












--------MEan-------
2.0
2.0
[[0 1 2]
 [3 4 5]
 [6 7 8]]
4.0
[3. 4. 5.]
[1 4 7]


-------------MEDIAN---------------
20.0
25.0

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4.0
[3. 4. 5.]
[1. 4. 7.]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
7.5
[6. 7. 8. 9.]
[ 1.5  5.5  9.5 13.5]

----------VARIANCE------------
2.0

[[0 1 2]
 [3 4 5]]
2.9166666666666665
[2.25 2.25 2.25]
[0.66666667 0.66666667]

----------STep deviation---------
1.4142135623730951

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]

---------Numpy mathematical functions------
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[0.         1.         1.41421356 1.73205081 2.        ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128]

------------Find Uniqu

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:63: RuntimeWarning: divide by zero encountered in log


In [ ]:
#Session - 29 
import numpy as np
a=np.arange(1,10).reshape(3,3)
print(a)
print(np.diag(a,k=0))
print(np.diag(a,k=1))
print(np.diag(a,k=-1))
print()
#For 1D
a=np.array([10,20,30,40])
print(np.diag(a,k=0))
print(np.diag(a,k=1))
print(np.diag(a,k=2))
print(np.diag(a,k=-1))
print(np.diag(a,k=-2))

print()
#Creation of ndarray with provided diagonal
a=np.diag([1,2,3])
print(a)
a=np.diag([1,2,3],k=1)
print(a)
a=np.diag([1,2,3],k=-1)
print(a)
print()

l=np.arange(1,20)
a=np.diag(l)
print(a)

print()
 
 






[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[2 6]
[4 8]

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
[[ 0 10  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 40]
 [ 0  0  0  0  0]]
[[ 0  0 10  0  0  0]
 [ 0  0  0 20  0  0]
 [ 0  0  0  0 30  0]
 [ 0  0  0  0  0 40]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]
[[ 0  0  0  0  0]
 [10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [10  0  0  0  0  0]
 [ 0 20  0  0  0  0]
 [ 0  0 30  0  0  0]
 [ 0  0  0 40  0  0]]

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
[[0 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]
[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0 